server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DBHOST:localhost}:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
